services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5001
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    entrypoint: ["/app/entrypoint.sh"]
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: flask_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
