import requests

# ─── CONFIG ───────────────────────────────────────────────────────────────────
API_URL = "https://matcha-2.onrender.com/api/auth/sign-up"

# Free image URLs — no storage needed
# randomuser.me  → realistic profile photos (gender-aware)
# picsum.photos  → random lifestyle/scenery photos (used for image2-4)

def get_images(sex: str, seed: int):
    """Return 4 image URLs for a user. image1 = profile photo, 2-4 = extras."""
    gender = "female" if sex == "female" else "male"
    num = (seed % 70) + 1  # randomuser has ~70 photos per gender
    return {
        "profile_image": f"https://randomuser.me/api/portraits/{gender}s/{num}.jpg",
        "image1": f"https://randomuser.me/api/portraits/{gender}s/{num}.jpg",
        "image2": f"https://picsum.photos/seed/{seed}a/400/400",
        "image3": f"https://picsum.photos/seed/{seed}b/400/400",
        "image4": f"https://picsum.photos/seed/{seed}c/400/400",
    }

# ─── USER DATA ────────────────────────────────────────────────────────────────
INDUSTRIES = ["technologie", "finance", "healthcare", "education", "marketing", "consulting"]

USERS = [
    {
        "email": "alice.martin@example.com",
        "username": "alice_m",
        "password": "Password123!",
        "first_name": "Alice",
        "last_name": "Martin",
        "age": "28",
        "sex": "female",
        "sexualPreference": "male",
        "location": "Paris, France",
        "emailVerified": "t",
        "title": "UX Designer",
        "company": "Pixelcraft",
        "industry": INDUSTRIES[0],
        "experienceLevel": "Mid-level",
        "education": "Bachelor's in Design",
        "bio": "Passionate about creating beautiful user experiences.",
"interests": ["Traveling", "Music", "Movies", "Photography", "Yoga", "Cooking"],
    },
    {
        "email": "bob.johnson@example.com",
        "username": "bobby_j",
        "password": "Password123!",
        "first_name": "Bob",
        "last_name": "Johnson",
        "age": "34",
        "sex": "male",
        "sexualPreference": "female",
        "location": "New York, USA",
        "emailVerified": "t",
        "title": "Software Engineer",
        "company": "TechNova",
        "industry": INDUSTRIES[1],
        "experienceLevel": "Senior",
        "education": "Master's in Computer Science",
        "bio": "Full-stack developer who loves open source.",
"interests": ["Gaming", "Coding", "Sports", "Cooking", "Hiking", "Movies"],
    },
    {
        "email": "clara.smith@example.com",
        "username": "clara_s",
        "password": "Password123!",
        "first_name": "Clara",
        "last_name": "Smith",
        "age": "26",
        "sex": "female",
        "sexualPreference": "everyone",
        "location": "London, UK",
        "emailVerified": "t",
        "title": "Marketing Manager",
        "company": "BrandWave",
        "industry": INDUSTRIES[2],
        "experienceLevel": "Mid-level",
        "education": "Bachelor's in Business",
        "bio": "Brand storyteller and coffee addict.",
"interests": ["Reading / Books", "Traveling", "Yoga", "Music", "Photography", "Cooking"],
    },
    {
        "email": "david.lee@example.com",
        "username": "dave_lee",
        "password": "Password123!",
        "first_name": "David",
        "last_name": "Lee",
        "age": "40",
        "sex": "male",
        "sexualPreference": "male",
        "location": "Seoul, South Korea",
        "emailVerified": "t",
        "title": "Product Manager",
        "company": "Kakao",
        "industry": INDUSTRIES[3],
        "experienceLevel": "Director",
        "education": "MBA",
        "bio": "Building products people actually love.",
"interests": ["Hiking", "Movies", "Cooking", "Sports", "Traveling", "Music"],
    },
    {
        "email": "emma.dubois@example.com",
        "username": "emma_d",
        "password": "Password123!",
        "first_name": "Emma",
        "last_name": "Dubois",
        "age": "31",
        "sex": "female",
        "sexualPreference": "male",
        "location": "Lyon, France",
        "emailVerified": "t",
        "title": "Data Scientist",
        "company": "Insight AI",
        "industry": INDUSTRIES[4],
        "experienceLevel": "Senior",
        "education": "Master's in Statistics",
        "bio": "Turning raw data into meaningful stories.",
"interests": ["Reading / Books", "Music", "Cooking", "Photography", "Traveling", "Yoga"],
    },
    {
        "email": "felix.garcia@example.com",
        "username": "felix_g",
        "password": "Password123!",
        "first_name": "Felix",
        "last_name": "Garcia",
        "age": "29",
        "sex": "male",
        "sexualPreference": "female",
        "location": "Madrid, Spain",
        "emailVerified": "t",
        "title": "Graphic Designer",
        "company": "Freelance",
        "industry": INDUSTRIES[5],
        "experienceLevel": "Mid-level",
        "education": "Bachelor's in Fine Arts",
        "bio": "Crafting visuals that speak louder than words.",
"interests": ["Movies", "Traveling", "Sports", "Music", "Photography", "Gaming"],
    },
    {
        "email": "grace.kim@example.com",
        "username": "grace_k",
        "password": "Password123!",
        "first_name": "Grace",
        "last_name": "Kim",
        "age": "27",
        "sex": "female",
        "sexualPreference": "female",
        "location": "Toronto, Canada",
        "emailVerified": "t",
        "title": "Frontend Developer",
        "company": "Shopify",
        "industry": INDUSTRIES[0],
        "experienceLevel": "Mid-level",
        "education": "Bachelor's in Computer Science",
        "bio": "React enthusiast and dark-mode advocate.",
"interests": ["Gaming", "Coding", "Reading / Books", "Yoga", "Movies", "Music"],
    },
    {
        "email": "henry.wilson@example.com",
        "username": "henry_w",
        "password": "Password123!",
        "first_name": "Henry",
        "last_name": "Wilson",
        "age": "45",
        "sex": "male",
        "sexualPreference": "female",
        "location": "Sydney, Australia",
        "emailVerified": "t",
        "title": "CTO",
        "company": "OceanTech",
        "industry": INDUSTRIES[1],
        "experienceLevel": "Executive",
        "education": "PhD in Engineering",
        "bio": "Leading teams to build scalable systems.",
"interests": ["Hiking", "Sports", "Cooking", "Traveling", "Music", "Movies"],
    },
    {
        "email": "isabella.rossi@example.com",
        "username": "isa_r",
        "password": "Password123!",
        "first_name": "Isabella",
        "last_name": "Rossi",
        "age": "24",
        "sex": "female",
        "sexualPreference": "male",
        "location": "Milan, Italy",
        "emailVerified": "t",
        "title": "Fashion Blogger",
        "company": "Self-employed",
        "industry": INDUSTRIES[2],
        "experienceLevel": "Entry-level",
        "education": "Bachelor's in Fashion Design",
        "bio": "Style is a way of saying who you are without speaking.",
"interests": ["Traveling", "Photography", "Music", "Cooking", "Yoga", "Reading / Books"],
    },
    {
        "email": "james.brown@example.com",
        "username": "james_b",
        "password": "Password123!",
        "first_name": "James",
        "last_name": "Brown",
        "age": "38",
        "sex": "male",
        "sexualPreference": "everyone",
        "location": "Chicago, USA",
        "emailVerified": "t",
        "title": "DevOps Engineer",
        "company": "CloudBase",
        "industry": INDUSTRIES[3],
        "experienceLevel": "Senior",
        "education": "Bachelor's in IT",
        "bio": "Automating everything so humans don't have to.",
"interests": ["Gaming", "Coding", "Sports", "Movies", "Hiking", "Traveling"],
    },
    {
        "email": "karen.nguyen@example.com",
        "username": "karen_n",
        "password": "Password123!",
        "first_name": "Karen",
        "last_name": "Nguyen",
        "age": "33",
        "sex": "female",
        "sexualPreference": "male",
        "location": "Ho Chi Minh City, Vietnam",
        "emailVerified": "t",
        "title": "Business Analyst",
        "company": "VinGroup",
        "industry": INDUSTRIES[4],
        "experienceLevel": "Mid-level",
        "education": "Master's in Business",
        "bio": "Data-driven decisions every single day.",
"interests": ["Reading / Books", "Yoga", "Traveling", "Music", "Photography", "Cooking"],
    },
    {
        "email": "luca.ferrari@example.com",
        "username": "luca_f",
        "password": "Password123!",
        "first_name": "Luca",
        "last_name": "Ferrari",
        "age": "30",
        "sex": "male",
        "sexualPreference": "female",
        "location": "Rome, Italy",
        "emailVerified": "t",
        "title": "Backend Developer",
        "company": "FinEdge",
        "industry": INDUSTRIES[5],
        "experienceLevel": "Senior",
        "education": "Master's in Computer Science",
        "bio": "Building the invisible layer that powers everything.",
"interests": ["Cooking", "Sports", "Movies", "Traveling", "Music", "Hiking"],
    },
    {
        "email": "mia.patel@example.com",
        "username": "mia_p",
        "password": "Password123!",
        "first_name": "Mia",
        "last_name": "Patel",
        "age": "25",
        "sex": "female",
        "sexualPreference": "male",
        "location": "Mumbai, India",
        "emailVerified": "t",
        "title": "Content Writer",
        "company": "MediaHub",
        "industry": INDUSTRIES[0],
        "experienceLevel": "Entry-level",
        "education": "Bachelor's in Journalism",
        "bio": "Words are my superpower.",
"interests": ["Reading / Books", "Music", "Photography", "Yoga", "Traveling", "Cooking"],
    },
    {
        "email": "noah.taylor@example.com",
        "username": "noah_t",
        "password": "Password123!",
        "first_name": "Noah",
        "last_name": "Taylor",
        "age": "36",
        "sex": "male",
        "sexualPreference": "female",
        "location": "Austin, USA",
        "emailVerified": "t",
        "title": "Startup Founder",
        "company": "LaunchPad",
        "industry": INDUSTRIES[1],
        "experienceLevel": "Founder",
        "education": "Bachelor's in Business",
        "bio": "Serial entrepreneur obsessed with solving problems.",
"interests": ["Hiking", "Coding", "Sports", "Traveling", "Gaming", "Music"],
    },
    {
        "email": "olivia.chen@example.com",
        "username": "olivia_c",
        "password": "Password123!",
        "first_name": "Olivia",
        "last_name": "Chen",
        "age": "29",
        "sex": "female",
        "sexualPreference": "everyone",
        "location": "Shanghai, China",
        "emailVerified": "t",
        "title": "AI Researcher",
        "company": "DeepMind",
        "industry": INDUSTRIES[2],
        "experienceLevel": "Senior",
        "education": "PhD in Machine Learning",
        "bio": "Making machines smarter, one model at a time.",
"interests": ["Reading / Books", "Coding", "Music", "Gaming", "Movies", "Yoga"],
    },
    {
        "email": "peter.hoffman@example.com",
        "username": "pete_h",
        "password": "Password123!",
        "first_name": "Peter",
        "last_name": "Hoffman",
        "age": "42",
        "sex": "male",
        "sexualPreference": "female",
        "location": "Berlin, Germany",
        "emailVerified": "t",
        "title": "Engineering Manager",
        "company": "SAPNext",
        "industry": INDUSTRIES[3],
        "experienceLevel": "Manager",
        "education": "Master's in Software Engineering",
        "bio": "Bridging the gap between code and people.",
"interests": ["Cooking", "Hiking", "Reading / Books", "Movies", "Traveling", "Sports"],
    },
    {
        "email": "quinn.morales@example.com",
        "username": "quinn_m",
        "password": "Password123!",
        "first_name": "Quinn",
        "last_name": "Morales",
        "age": "27",
        "sex": "female",
        "sexualPreference": "female",
        "location": "Buenos Aires, Argentina",
        "emailVerified": "t",
        "title": "Social Media Manager",
        "company": "Trendify",
        "industry": INDUSTRIES[4],
        "experienceLevel": "Mid-level",
        "education": "Bachelor's in Communications",
        "bio": "Growing communities one post at a time.",
"interests": ["Photography", "Traveling", "Music", "Movies", "Yoga", "Cooking"],
    },
    {
        "email": "ryan.oconnor@example.com",
        "username": "ryan_oc",
        "password": "Password123!",
        "first_name": "Ryan",
        "last_name": "O'Connor",
        "age": "31",
        "sex": "male",
        "sexualPreference": "male",
        "location": "Dublin, Ireland",
        "emailVerified": "t",
        "title": "Cybersecurity Analyst",
        "company": "SecureNet",
        "industry": INDUSTRIES[5],
        "experienceLevel": "Mid-level",
        "education": "Bachelor's in Network Security",
        "bio": "Keeping the bad guys out since 2015.",
"interests": ["Gaming", "Coding", "Hiking", "Sports", "Movies", "Music"],
    },
    {
        "email": "sophie.laurent@example.com",
        "username": "sophie_l",
        "password": "Password123!",
        "first_name": "Sophie",
        "last_name": "Laurent",
        "age": "35",
        "sex": "female",
        "sexualPreference": "male",
        "location": "Brussels, Belgium",
        "emailVerified": "t",
        "title": "HR Director",
        "company": "PeopleFirst",
        "industry": INDUSTRIES[0],
        "experienceLevel": "Director",
        "education": "Master's in HR Management",
        "bio": "People are the most valuable asset in any company.",
"interests": ["Yoga", "Reading / Books", "Traveling", "Cooking", "Music", "Photography"],
    },
    {
        "email": "tom.nakamura@example.com",
        "username": "tom_n",
        "password": "Password123!",
        "first_name": "Tom",
        "last_name": "Nakamura",
        "age": "37",
        "sex": "male",
        "sexualPreference": "female",
        "location": "Tokyo, Japan",
        "emailVerified": "t",
        "title": "Game Developer",
        "company": "NinjaStudio",
        "industry": INDUSTRIES[1],
        "experienceLevel": "Senior",
        "education": "Bachelor's in Computer Science",
        "bio": "Crafting worlds where players get lost for hours.",
"interests": ["Gaming", "Movies", "Music", "Sports", "Coding", "Traveling"],
    },
]

# ─── SEND REQUESTS ────────────────────────────────────────────────────────────
def seed_users():
    print(f"🚀 Seeding {len(USERS)} users to {API_URL}\\n")
    success, failed = 0, 0

    for i, user in enumerate(USERS, 1):
        # Attach the 4 image URLs (no local files needed)
        payload = {**user, **get_images(user["sex"], i)}

        print(f"[{i:02d}/20] Sending → {user['username']} ({user['email']}) ...", end=" ")

        try:
            resp = requests.post(API_URL, json=payload, timeout=15)
            if resp.status_code in (200, 201):
                print(f"✅  {resp.status_code}")
                success += 1
            else:
                print(f"❌  {resp.status_code}  {resp.text[:120]}")
                failed += 1
        except requests.exceptions.ConnectionError:
            print("❌  Connection refused — is the server running?")
            failed += 1
        except Exception as e:
            print(f"❌  {e}")
            failed += 1

    print(f"\\n{'─'*40}")
    print(f"Done! ✅ {success} created   ❌ {failed} failed")

if __name__ == "__main__":
    seed_users()

